# Generated by Django 5.2.6 on 2025-09-15 01:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('name', models.CharField(max_length=50, verbose_name='Название сбора')),
                ('cause', models.CharField(choices=[('BD', 'Birthday'), ('WD', 'Wedding'), ('PT', 'Party'), ('MD', 'Medicine'), ('AR', 'Art')], default='AR', max_length=2, verbose_name='Повод сбора')),
                ('description', models.TextField(verbose_name='Описание сбора')),
                ('planned_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Планируемая сумма сбора')),
                ('image', models.ImageField(blank=True, null=True, upload_to='collects/images/', verbose_name='Обложка сбора')),
                ('closing_to', models.DateTimeField(verbose_name='Дата и время завершения сбора')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Владелец сбора')),
            ],
            options={
                'verbose_name': 'Сбор',
                'verbose_name_plural': 'Сборы',
                'ordering': ('-created_at',),
                'default_related_name': 'collections',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('comment', models.CharField(max_length=50, verbose_name='Комментарий к платежу')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма пожертвования')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Владелец платежа')),
                ('collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fees.collect', verbose_name='Оплата сбора')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'ordering': ('-created_at',),
                'default_related_name': 'payments',
            },
        ),
    ]
