# Generated by Django 5.2.6 on 2025-09-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collect',
            name='closed',
            field=models.BooleanField(default=False, verbose_name='Сбор закрыт'),
        ),
    ]
