# Generated by Django 5.2.6 on 2025-09-12 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collect',
            name='count_supporters',
        ),
    ]
