# Generated by Django 5.2.6 on 2025-09-14 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_collect_closed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collect',
            name='closed',
        ),
    ]
