# Generated by Django 5.2.6 on 2025-09-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_remove_collect_count_supporters'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Сумма пожертвования'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collect',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='collects/images/', verbose_name='Обложка сбора'),
        ),
    ]
