# Generated by Django 5.2.6 on 2025-09-14 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0003_remove_collect_closed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='owner',
            new_name='author',
        ),
    ]
