# Generated by Django 5.2.6 on 2025-09-13 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0004_alter_payment_options_alter_collect_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='name',
            new_name='comment',
        ),
    ]
